# Use the official Golang image
FROM golang:1.22-alpine

# Set the working directory inside the container
WORKDIR /user/local/src

# Copy the local package files to the container's workspace
COPY ["go.mod", "go.sum", "./"]

# Build the Go app
RUN go build -o main .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
